src/Entity/Session.php
<?php

namespace App\Entity;

use App\DTO\SessionWithDetail;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SessionRepository")
 */
class Session
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100, nullable=true, unique=true)
     */
    private $importKey;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $stop;

    /**
     * @var boolean
     * @ORM\Column(type="boolean")
     */
    private $cancelled;

    /**
     * @var boolean
     * @ORM\Column(type="boolean", options={ "default": false })
     */
    private $highlight;

    /**
     * @var ?SessionDetail
     * @ORM\OneToOne(targetEntity="App\Entity\SessionDetail", cascade={"persist", "remove"}, orphanRemoval=false)
     * @ORM\JoinColumn(nullable=false)
     */
    private $draftDetails;

    /**
     * @var ?SessionDetail
     * @ORM\OneToOne(targetEntity="App\Entity\SessionDetail", cascade={"persist", "remove"}, orphanRemoval=false)
     */
    private $proposedDetails;

    /**
     * @var ?SessionDetail
     * @ORM\OneToOne(targetEntity="App\Entity\SessionDetail", cascade={"persist", "remove"}, orphanRemoval=false)
     */
    private $acceptedDetails;

    /**
     * @var ?Organization
     * @ORM\ManyToOne(targetEntity="App\Entity\Organization", inversedBy="sessions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organization;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $acceptedAt;

    public function __construct()
    {
        $this->setCancelled(false);
        $this->setHighlight(false);
        $this->setDraftDetails(new SessionDetail());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getImportKey(): ?string
    {
        return $this->importKey;
    }

    /**
     * @param string|null $importKey
     * @return Session
     */
    public function setImportKey(?string $importKey): self
    {
        $this->importKey = $importKey;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(?\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getStop(): ?\DateTimeInterface
    {
        return $this->stop;
    }

    public function setStop(?\DateTimeInterface $stop): self
    {
        $this->stop = $stop;

        return $this;
    }

    public function getCancelled(): ?bool
    {
        return $this->cancelled;
    }

    public function setCancelled(bool $cancelled): self
    {
        $this->cancelled = $cancelled;

        return $this;
    }

    public function isHighlight(): bool
    {
        return $this->highlight;
    }

    public function setHighlight(bool $highlight): Session
    {
        $this->highlight = $highlight;
        return $this;
    }

    public function getDraftDetails(): ?SessionDetail
    {
        return $this->draftDetails;
    }

    public function setDraftDetails(SessionDetail $draftDetails): self
    {
        $this->draftDetails = $draftDetails;

        return $this;
    }

    public function getProposedDetails(): ?SessionDetail
    {
        return $this->proposedDetails;
    }

    public function setProposedDetails(SessionDetail $proposedDetails): self
    {
        $this->proposedDetails = $proposedDetails;

        return $this;
    }

    public function getAcceptedDetails(): ?SessionDetail
    {
        return $this->acceptedDetails;
    }

    public function setAcceptedDetails(?SessionDetail $acceptedDetails): self
    {
        $this->acceptedDetails = $acceptedDetails;

        return $this;
    }

    public function isAccepted(): bool
    {
        return $this->acceptedDetails === $this->proposedDetails && $this->acceptedDetails !== null;
    }

    public function isAcceptedAndChanged(): bool
    {
        return $this->acceptedDetails !== null && $this->acceptedDetails !== $this->proposedDetails;
    }

    public function isProposed(): bool
    {
        return $this->proposedDetails !== null;
    }

    public function hasDraft(): bool
    {
        return $this->proposedDetails !== $this->draftDetails;
    }

    public function toSessionWithDetail(bool $withProposedDetails): SessionWithDetail
    {
        $details = $withProposedDetails ? $this->getProposedDetails() : $this->getDraftDetails();

        return (new SessionWithDetail())
            ->setId($this->getId())
            ->setDate($this->getStart())
            ->setStart($this->getStart())
            ->setStop($this->getStop())
            ->setOrganization($this->getOrganization())
            ->setChannel($details->getChannel())
            ->setOnlineOnly($details->getOnlineOnly())
            ->setTitle($details->getTitle())
            ->setShortDescription($details->getShortDescription())
            ->setLongDescription($details->getLongDescription())
            ->setLocation($details->getLocation())
            ->setLocationLat($details->getLocationLat())
            ->setLocationLng($details->getLocationLng())
            ->setLink($details->getLink());
    }

    public function applyDetails(SessionWithDetail $sessionWithDetail): self
    {
        $start = (new \DateTime())
            ->setDate(
                (int) $sessionWithDetail->getDate()->format('Y'),
                (int) $sessionWithDetail->getDate()->format('m'),
                (int) $sessionWithDetail->getDate()->format('d')
            )
            ->setTime(
                (int) $sessionWithDetail->getStart()->format('H'),
                (int) $sessionWithDetail->getStart()->format('i')
            );

        $stop =
            $sessionWithDetail->getStop() === null
                ? null
                : (new \DateTime())
                    ->setDate(
                        (int) $sessionWithDetail->getDate()->format('Y'),
                        (int) $sessionWithDetail->getDate()->format('m'),
                        (int) $sessionWithDetail->getDate()->format('d')
                    )
                    ->setTime(
                        (int) $sessionWithDetail->getStop()->format('H'),
                        (int) $sessionWithDetail->getStop()->format('i')
                    );

        if (
            $this->getStart() === null &&
            $this->getAcceptedDetails() !== null &&
            $this->getAcceptedDetails()->differs($sessionWithDetail)
        ) {
            // If user re-uses an existing, already accepted start=null session, and also updates the details,
            // then re-trigger the editing process.
            $this->setDraftDetails(new SessionDetail());
            $this->setAcceptedDetails(null);
        }

        $this->setStart($start)
            ->setStop($stop)
            ->setOrganization($sessionWithDetail->getOrganization());

        if (!$this->getDraftDetails()->differs($sessionWithDetail)) {
            return $this;
        }

        if (
            $this->getDraftDetails() === $this->getAcceptedDetails() ||
            $this->getDraftDetails() === $this->getProposedDetails()
        ) {
            $this->setDraftDetails(new SessionDetail());
        }

        $this->getDraftDetails()->apply($sessionWithDetail);

        return $this;
    }

    public function propose()
    {
        $this->setProposedDetails($this->getDraftDetails());
    }

    public function accept()
    {
        $this->setAcceptedDetails($this->getProposedDetails())->setAcceptedAt(new \DateTimeImmutable('now'));
    }

    public function getOrganization(): ?Organization
    {
        return $this->organization;
    }

    public function setOrganization(?Organization $organization): self
    {
        $this->organization = $organization;

        return $this;
    }

    public function getAcceptedAt(): ?\DateTimeInterface
    {
        return $this->acceptedAt;
    }

    public function setAcceptedAt(?\DateTimeInterface $acceptedAt): self
    {
        $this->acceptedAt = $acceptedAt;

        return $this;
    }
}

templates/session/_cancel_form.html.twig
<form class="inline" method="post" action="{{ path('session_cancel', {'id': session.id}) }}" onsubmit="return confirm('Bist du sicher, dass du das Event absagen möchtest?');">
    <input type="hidden" name="_token" value="{{ csrf_token('cancel' ~ session.id) }}">
    <button class="btn btn-sm btn-outline-danger" title="absagen"><i class="fa fa-times"></i></button>
</form>

templates/session/_delete_form.html.twig
<form class="inline" method="post" action="{{ path('session_delete', {'id': session.id}) }}" onsubmit="return confirm('Bist du sicher, dass du das Event löschen möchtest?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ session.id) }}">
    <button class="btn btn-sm btn-outline-danger" title="löschen"><i class="fa fa-trash"></i></button>
</form>

templates/session/_form.html.twig
{{ form_start(form) }}

<h2>Wann?</h2>
{{ form_row(form.date) }}
{{ form_row(form.start) }}
{{ form_row(form.stop) }}
<div id="parallel-session-hint-box"></div>

<h2>Worum geht's?</h2>

{{ form_row(form.title) }}

<div class="alert alert-info" role="alert" style="margin-top: 2rem">
    <p>
        Bitte beschreibe dein Event zunächst mit einem (kurzen) Teaser-Text. Ein Absatz. Worum geht's?
        Wer ist die Zielgruppe?<br/>
        In der Detailbeschreibung kannst du konkreter werden. Im Veranstaltungskalender werden beide Texte
        übereinander angezeigt.
    </p>
</div>

{{ form_row(form.shortDescription) }}
{{ form_row(form.longDescription) }}

<div class="alert alert-info" role="alert">
    <p><strong>Kategorien – darum geht's</strong></p>

    <p>
        Die WueWW hatte letztes Jahr 176 Veranstaltungen an den acht Veranstaltungstagen. Von vielen kam der Wunsch nach
        Filtern, um nicht von der schieren Masse an Terminen erschlagen zu werden.
    </p>

    <p>
        Wir haben uns daher entschieden, euch Kategorien vorzuschlagen und sie entsprechend farblich im Progamm auf der
        Webseite darzustellen.
    </p>

    <p>
        Bitte wähle jetzt die Kategorie aus, die auf dein Event am besten zutrifft. Das wird vielleicht nicht immer zu
        100 Prozent passen. Du hilfst damit aber anderen, einen besseren Überblick zu bekommen und davon profitieren wir
        alle: Veranstalter und Teilnehmer (m/w/d) und so auch die WueWW. Danke!
    </p>
</div>

{{ form_row(form.channel) }}

<h2>Veranstaltungsort</h2>

{{ form_widget(form.onlineOnly) }}

<div class="alert alert-info" role="alert" style="margin-top: 1rem">
    <p>
        Erfasst Hinweise, wie man bei eurer Online-Veranstaltung teilnehmen kann, bitte oben mit in der Langbeschreibung
        (welche Software wird verwendet, wann bekommt man wie die Zugangsdaten usw.).
    </p>
</div>

<div id="offline-session-details">
    {{ form_widget(form.location) }}

    <label>Position der Location auf der Karte (Eingang zum Gebäude, zum Festlegen Karte anklicken)</label>
    <div id="map"></div>
</div>

<h2>Sonstiges</h2>
{{ form_rest(form) }}

{% if is_granted('ROLE_EDITOR') %}
    <button class="btn btn-primary">Speichern</button>
{% else %}
    <button class="btn btn-light" name="draft">Entwurf speichern</button>
    <button class="btn btn-primary">Speichern und zur Freigabe geben</button>
{% endif %}

{{ form_end(form) }}

templates/session/_orgdata_missing_info.html.twig
{% if not is_granted('ROLE_EDITOR') and (app.user.organizations.first.proposedOrganizationDetails is null or app.user.organizations.first.proposedOrganizationDetails.title == "") %}
    <div class="alert alert-warning" role="alert">
        <p>
            Aktuell sind die Veranstalterdaten nicht, oder nicht vollständig, erfasst. Diese müssen gepflegt werden,
            ehe ein Event veröffentlicht werden kann.
        </p>

        <a class="btn btn-warning" href="{{ path('my_organization') }}">Veranstalterangaben pflegen</a>
    </div>
{% endif %}

templates/session/_orgdata_not_accepted.html.twig
{% if session.organization.proposedOrganizationDetails is not null and session.organization.acceptedOrganizationDetails is null %}
    <div class="alert alert-warning" role="alert">
        <p>
            Die Veranstalterdaten wurden bislang nicht zur Veröffentlichung freigeschaltet. Es können bereits
            Events erfasst werden - diese bleiben bis zur Freigabe jedoch unveröffentlicht.
        </p>
    </div>
{% endif %}

templates/session/_remove_approval_form.html.twig
<form class="inline" method="post" action="{{ path('session_remove_approval', {'id': session.id}) }}" onsubmit="return confirm('Bist du sicher, dass du die Freigabe des Events zurückziehen möchtest?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('remove_approval' ~ session.id) }}">
    <button class="btn btn-sm btn-outline-danger" title="Freigabe zurückziehen"><i class="fa fa-undo"></i></button>
</form>

templates/session/_toggle_highlight_form.html.twig
<form class="inline" method="post" action="{{ path('session_toggle_highlight', {'id': session.id}) }}">
    <input type="hidden" name="_token" value="{{ csrf_token('toggle_highlight' ~ session.id) }}">
    <button class="btn btn-sm btn-outline-secondary" title="{% if session.highlight %}Highlight-Markierung entfernen{% else %}als Highlight markieren{% endif %}"><i class="fa fa-star"></i></button>
</form>

templates/session/diff.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    {{ include('session/_orgdata_missing_info.html.twig') }}
    {{ include('session/_orgdata_not_accepted.html.twig') }}

    <h1>Änderungen am Event</h1>

    {% if session.start is null %}
        <div class="alert alert-danger" role="alert">
            <p>
                Aktuell ist kein Beginn-Zeitpunkt erfasst. Das Event wird daher nicht veröffentlicht.
            </p>
        </div>
    {% endif %}

    <table class="table highlight-diff">
        <tbody>
        <tr>
            <th>Beginn</th>
            <td>{{ session.start ? session.start|date('d.m.Y H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>Ende</th>
            <td>{{ session.stop ? session.stop|date('d.m.Y H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>Abgesagt?</th>
            <td>{{ session.cancelled ? 'Ja' : 'Nein' }}</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
            <th>Titel</th>
            <td>{{ session.proposedDetails.title | diff(session.acceptedDetails.title) }}</td>
        </tr>
        <tr>
            <th>Teaser-Text</th>
            <td>{{ session.proposedDetails.shortDescription | diff(session.acceptedDetails.shortDescription) | nl2br }}</td>
        </tr>
        <tr>
            <th>Detaillierte Beschreibung</th>
            <td>{{ session.proposedDetails.longDescription | diff(session.acceptedDetails.longDescription) | nl2br }}</td>
        </tr>
        <tr>
            <th>Veranstaltungsort</th>
            <td>
                {% if session.proposedDetails.onlineOnly %}
                    <em>findet ausschließlich online statt</em>
                {% else %}
                    {{ session.proposedDetails.location.name | diff(session.acceptedDetails.location.name) }},
                    {{ session.proposedDetails.location.streetNo | diff(session.acceptedDetails.location.streetNo) }},
                    {{ session.proposedDetails.location.zipcode | diff(session.acceptedDetails.location.zipcode) }}
                    {{ session.proposedDetails.location.city | diff(session.acceptedDetails.location.city) }}
                {% endif %}
            </td>
        </tr>

        <tr>
            <th>Link</th>
            <td>
                {% if "@" in session.proposedDetails.link %}
                    <i class="fa fa-envelope"></i>
                    <a href="mailto:{{ session.proposedDetails.link }}">{{ session.proposedDetails.link | diff(session.acceptedDetails.link) }}</a>
                {% else %}
                    <a href="{{ session.proposedDetails.link }}"
                       target="_blank">{{ session.proposedDetails.link | diff(session.acceptedDetails.link) }}</a>
                {% endif %}
            </td>
        </tr>
        </tbody>
    </table>

    <h2>Veranstalter</h2>

    <table class="table">
        <tbody>
        {% if session.organization.proposedOrganizationDetails %}
            <tr>
                <th>Titel</th>
                <td>{{ session.organization.proposedOrganizationDetails.title }}</td>
            </tr>
            <tr>
                <th>Ansprechpartner</th>
                <td>{{ session.organization.proposedOrganizationDetails.contactName }}</td>
            </tr>
        {% endif %}
        <tr>
            <th>E-Mail-Adresse</th>
            <td>
                <i class="fa fa-envelope"></i>
                <a href="mailto:{{ session.organization.owner.email }}">{{ session.organization.owner.email }}</a>
            </td>
        </tr>
        </tbody>
    </table>

    <form class="inline pull-right" method="post" action="{{ path('session_accept', {'id': session.id}) }}">
        <input type="hidden" name="_token" value="{{ csrf_token('accept' ~ session.id) }}">
        <button class="btn btn-primary"><i class="fa fa-check"></i> Event freigeben</button>
    </form>

    <a href="{{ path('session_index') }}">zurück zur Eventliste</a>

{% endblock %}

templates/session/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ include('session/_orgdata_missing_info.html.twig') }}
    {{ include('session/_orgdata_not_accepted.html.twig') }}

    <h1>Event bearbeiten</h1>

    {% if session.start is null %}
        <div class="alert alert-danger" role="alert">
            <p>
                Aktuell ist kein Beginn-Zeitpunkt (mehr) erfasst. Bitte neues Datum und Uhrzeit für das Event festlegen.
            </p>
        </div>
    {% endif %}

    {{ include('session/_form.html.twig') }}

    <a href="{{ path('session_index') }}">zurück zur Eventliste</a>
{% endblock %}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ include('session/_orgdata_missing_info.html.twig') }}

    <h1>Eventliste</h1>

    {% if is_granted('ROLE_EDITOR') %}
        Filter: <a href="?">alle</a> | <a href="?has_changes">nicht freigegebene Änderungen</a> | <a
            href="?not_approved">ohne Freigabe</a>
    {% endif %}


    <table class="table table-striped">
        <thead>
        <tr>
            <th>Datum</th>
            <th>Beginn</th>
            <th>Ende</th>
            <th>Titel</th>
            <th>Freigabe</th>
            {% if is_granted('ROLE_EDITOR') %}
            <th>Highlight</th>
            {% endif %}
            <th>Aktionen</th>
        </tr>
        </thead>
        <tbody>
        {% for session in sessions %}
            <tr class="{% if session.cancelled %}session-cancelled{% endif %}">
                <td>{{ session.start ? session.start|date('d.m.Y') : '-' }}</td>
                <td>{{ session.start ? session.start|date('H:i') : '-' }}</td>
                <td>{{ session.stop ? session.stop|date('H:i') : '-' }}</td>
                <td>{% if is_granted('ROLE_EDITOR') %}{{ session.proposedDetails.title }}{% else %}{{ session.draftDetails.title }}{% endif %}</td>
                <td>
                    {% if session.cancelled %}
                    {% elseif session.accepted %}
                        <i class="fa fa-check" title="freigegeben"></i>
                    {% elseif session.proposed %}
                        <i class="fa fa-hourglass-2" title="warten auf Freigabe"></i>
                    {% else %}
                        <i class="fa fa-pencil" title="Entwurf"></i>
                    {% endif %}
                </td>
                {% if is_granted('ROLE_EDITOR') %}
                <td>
                    {% if session.highlight %}
                        <i class="fa fa-star" title="Highlight"></i>
                    {% endif %}
                </td>
                {% endif %}
                <td class="session-actions">
                    <a class="btn btn-outline-secondary btn-sm" title="anzeigen"
                       href="{{ path('session_show', {'id': session.id}) }}"><i class="fa fa-eye"></i></a>

                    {% if is_granted('ROLE_EDITOR') and session.acceptedAndChanged %}
                        <a class="btn btn-outline-secondary btn-sm" title="Änderungen vergleichen"
                           href="{{ path('session_diff', {'id': session.id}) }}"><i class="fa fa-search"></i></a>
                    {% endif %}

                    {% if is_granted('ROLE_EDITOR') and session.accepted %}
                        {{ include('session/_toggle_highlight_form.html.twig') }}
                    {% endif %}

                    {% if not session.cancelled %}
                        <a class="btn btn-outline-secondary btn-sm" title="bearbeiten"
                           href="{{ path('session_edit', {'id': session.id}) }}"><i class="fa fa-pencil"></i></a>
                        {{ include('session/_cancel_form.html.twig') }}
                    {% endif %}
                    {% if is_granted('ROLE_EDITOR') %}
                        {{ include('session/_delete_form.html.twig') }}

                        {% if session.accepted %}
                            {{ include('session/_remove_approval_form.html.twig') }}
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="{% if is_granted('ROLE_EDITOR') -%}7{% else -%}6{% endif -%}">Keine Events gefunden.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if not is_granted('ROLE_EDITOR') %}
        <a class="btn btn-success" href="{{ path('session_new') }}">Neues Event vorschlagen</a>
    {% endif %}
{% endblock %}

templates/session/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ include('session/_orgdata_missing_info.html.twig') }}
    {{ include('session/_orgdata_not_accepted.html.twig') }}

    <h1>Neues Event vorschlagen</h1>

    {{ include('session/_form.html.twig') }}

    <a href="{{ path('session_index') }}">zurück zur Eventliste</a>
{% endblock %}

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    {{ include('session/_orgdata_missing_info.html.twig') }}
    {{ include('session/_orgdata_not_accepted.html.twig') }}

    <h1>Event</h1>

    {% if session.start is null %}
        <div class="alert alert-danger" role="alert">
            <p>
                Aktuell ist kein Beginn-Zeitpunkt erfasst. Das Event wird daher nicht veröffentlicht.
            </p>
        </div>
    {% endif %}

    {% if is_granted('ROLE_EDITOR') -%}
        {% set detail = session.proposedDetails -%}
    {% else -%}
        {% set detail = session.draftDetails -%}
    {% endif -%}

    <table class="table">
        <tbody>
        <tr>
            <th>Beginn</th>
            <td>{{ session.start ? session.start|date('d.m.Y H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>Ende</th>
            <td>{{ session.stop ? session.stop|date('d.m.Y H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>Abgesagt?</th>
            <td>{{ session.cancelled ? 'Ja' : 'Nein' }}</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
            <th>Kategorie</th>
            <td>
                {% if detail.channel %}
                    {{ detail.channel.name }}
                {% else %}
                    <em>keine Angabe</em>
                {% endif %}
            </td>
        </tr>
        <tr>
            <th>Titel</th>
            <td>{{ detail.title }}</td>
        </tr>
        <tr>
            <th>Beschreibung</th>
            <td>
                <p><strong>{{ detail.shortDescription | nl2br }}</strong></p>
                <p>{{ detail.longDescription | nl2br }}</p>
            </td>
        </tr>
        <tr>
            <th>Veranstaltungsort</th>
            <td>
                {% if detail.onlineOnly %}
                    <em>findet ausschließlich online statt</em>
                {% else %}
                    {{ detail.location.name }}, {{ detail.location.streetNo }},
                    {{ detail.location.zipcode }} {{ detail.location.city }}
                {% endif %}
            </td>
        </tr>
        {% if not detail.onlineOnly %}
            <tr>
                <th>Karte</th>
                <td>
                    <form autocomplete="off">
                        <input type="hidden" id="session_with_detail_locationLat"
                               value="{{ detail.locationLat }}"/>
                        <input type="hidden" id="session_with_detail_locationLng"
                               value="{{ detail.locationLng }}"/>
                        <div id="map" class="readonly"></div>
                    </form>
                </td>
            </tr>
        {% endif %}
        <tr>
            <th>Link</th>
            <td>
                {% if "@" in detail.link %}
                    <i class="fa fa-envelope"></i>
                    <a href="mailto:{{ detail.link }}">{{ detail.link }}</a>
                {% else %}
                    <a href="{{ detail.link }}" target="_blank">{{ detail.link }}</a>
                {% endif %}
            </td>
        </tr>
        </tbody>
    </table>

    {% if is_granted('ROLE_EDITOR') %}
        <h2>Veranstalter</h2>

        <table class="table">
            <tbody>
            {% if session.organization.proposedOrganizationDetails %}
                <tr>
                    <th>Titel</th>
                    <td>{{ session.organization.proposedOrganizationDetails.title }}</td>
                </tr>
                <tr>
                    <th>Ansprechpartner</th>
                    <td>{{ session.organization.proposedOrganizationDetails.contactName }}</td>
                </tr>
            {% endif %}
            <tr>
                <th>E-Mail-Adresse</th>
                <td>
                    <i class="fa fa-envelope"></i>
                    <a href="mailto:{{ session.organization.owner.email }}">{{ session.organization.owner.email }}</a>
                </td>
            </tr>
            </tbody>
        </table>
    {% endif %}

    {% if session.accepted %}
        <div class="alert alert-success" role="alert">
            Dieses Event ist bereits freigegeben.
        </div>

        {% if session.hasDraft %}
            <div class="alert alert-info" role="alert">
                Zu diesem Event existieren Änderungen, die jedoch noch nicht zur Freigabe eingereicht wurden.
            </div>
        {% endif %}
    {% elseif session.proposed %}
        <div class="alert alert-info clearfix" role="alert">
            Dieses Event wurde {% if session.acceptedDetails %}(in dieser Version){% endif %} bisher nicht freigegeben.

            {% if is_granted('ROLE_EDITOR') %}
                <form class="inline pull-right" method="post" action="{{ path('session_accept', {'id': session.id}) }}">
                    <input type="hidden" name="_token" value="{{ csrf_token('accept' ~ session.id) }}">
                    <button class="btn btn-primary"><i class="fa fa-check"></i> Event freigeben</button>
                </form>
            {% endif %}
        </div>
    {% else %}
        <div class="alert alert-info" role="alert">
            Dieses Event wurde bisher nicht zur Freigabe eingereicht.
        </div>
    {% endif %}

    <a href="{{ path('session_index') }}">zurück zur Eventliste</a>

{% endblock %}